services:
  backend: 
    container_name: nest_backend
    build:
      context: .
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - ACCESS_TOKENJWT_SECRET=${ACCESS_TOKENJWT_SECRET}
      - REFRESH_TOKENJWT_SECRET=${REFRESH_TOKENJWT_SECRET}
      - ACCESS_TOKEN_EXPIRATION_HOURS=${ACCESS_TOKEN_EXPIRATION_HOURS}
      - REFRESH_TOKEN_EXPIRATION_HOURS=${REFRESH_TOKEN_EXPIRATION_HOURS}
    ports:
      - "3000:3000"
    restart: always

  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456789
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin-data:
